# Generated by Django 3.1.7 on 2021-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-entryTime']},
        ),
    ]
