# Generated by Django 3.1.7 on 2021-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20210406_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created']},
        ),
    ]
