# Generated by Django 3.1.7 on 2021-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_on']},
        ),
    ]
