# Generated by Django 3.1.7 on 2021-05-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20210509_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_on']},
        ),
    ]
